class ScheduledPost < ApplicationRecord
	belongs_to :user
	belongs_to :account, optional: true
	belongs_to :topic, optional: true
	belongs_to :micropost, optional: true

	validates :post_time, presence: true
	validates :picture_url, presence: true
	validates :caption, presence: true
	validates :platform, presence: true

	def self.timezone_select_arr
		#arr = ActiveSupport::TimeZone::MAPPING.map { |key, value| [key, value] }
		arr = [
					["GMT(-12:00) - International Date Line West", "Etc/GMT+12"], 
					["GMT(-11:00) - Midway Island", "Pacific/Midway"], 
					["GMT(-11:00) - American Samoa", "Pacific/Pago_Pago"], 
					["GMT(-10:00) - Hawaii", "Pacific/Honolulu"], 
					["GMT(-9:00) - Alaska", "America/Juneau"], 
					["GMT(-8:00) - Pacific Time (US & Canada)", "America/Los_Angeles"], 
					["GMT(-8:00) - Tijuana", "America/Tijuana"], 
					["GMT(-7:00) - Mountain Time (US & Canada)", "America/Denver"], 
					["GMT(-7:00) - Arizona", "America/Phoenix"], 
					["GMT(-7:00) - Chihuahua", "America/Chihuahua"], 
					["GMT(-7:00) - Mazatlan", "America/Mazatlan"], 
					["GMT(-6:00) - Central Time (US & Canada)", "America/Chicago"], 
					["GMT(-6:00) - Saskatchewan", "America/Regina"], 
					["GMT(-6:00) - Guadalajara", "America/Mexico_City"], 
					["GMT(-6:00) - Mexico City", "America/Mexico_City"], 
					["GMT(-6:00) - Monterrey", "America/Monterrey"], 
					["GMT(-6:00) - Central America", "America/Guatemala"], 
					["GMT(-5:00) - Eastern Time (US & Canada)", "America/New_York"], 
					["GMT(-5:00) - Indiana (East)", "America/Indiana/Indianapolis"], 
					["GMT(-5:00) - Bogota", "America/Bogota"], 
					["GMT(-5:00) - Lima", "America/Lima"], 
					["GMT(-5:00) - Quito", "America/Lima"], 
					["GMT(-4:00) - Atlantic Time (Canada)", "America/Halifax"], 
					["GMT(-4:00) - Caracas", "America/Caracas"], 
					["GMT(-4:00) - La Paz", "America/La_Paz"], 
					["GMT(-4:00) - Santiago", "America/Santiago"], 
					["GMT(-3:30) - Newfoundland", "America/St_Johns"], 
					["GMT(-3:00) - Brasilia", "America/Sao_Paulo"], 
					["GMT(-3:00) - Buenos Aires", "America/Argentina/Buenos_Aires"], 
					["GMT(-3:00) - Montevideo", "America/Montevideo"], 
					["GMT(-4:00) - Georgetown", "America/Guyana"], 
					["GMT(-4:00) - Puerto Rico", "America/Puerto_Rico"], 
					["GMT(-3:00) - Greenland", "America/Godthab"], 
					["GMT(-2:00) - Mid-Atlantic", "Atlantic/South_Georgia"], 
					["GMT(-1:00) - Azores", "Atlantic/Azores"], 
					["GMT(-1:00) - Cape Verde Is:", "Atlantic/Cape_Verde"], 
					["GMT(0:00) - Dublin", "Europe/Dublin"], 
					["GMT(0:00) - Edinburgh", "Europe/London"], 
					["GMT(0:00) - Lisbon", "Europe/Lisbon"], 
					["GMT(0:00) - London", "Europe/London"], 
					["GMT(0:00) - Casablanca", "Africa/Casablanca"], 
					["GMT(0:00) - Monrovia", "Africa/Monrovia"], 
					["GMT(0:00) - UTC", "Etc/UTC"], 
					["GMT(+1:00) - Belgrade", "Europe/Belgrade"], 
					["GMT(+1:00) - Bratislava", "Europe/Bratislava"], 
					["GMT(+1:00) - Budapest", "Europe/Budapest"], 
					["GMT(+1:00) - Ljubljana", "Europe/Ljubljana"], 
					["GMT(+1:00) - Prague", "Europe/Prague"], 
					["GMT(+1:00) - Sarajevo", "Europe/Sarajevo"], 
					["GMT(+1:00) - Skopje", "Europe/Skopje"], 
					["GMT(+1:00) - Warsaw", "Europe/Warsaw"], 
					["GMT(+1:00) - Zagreb", "Europe/Zagreb"], 
					["GMT(+1:00) - Brussels", "Europe/Brussels"], 
					["GMT(+1:00) - Copenhagen", "Europe/Copenhagen"], 
					["GMT(+1:00) - Madrid", "Europe/Madrid"], 
					["GMT(+1:00) - Paris", "Europe/Paris"], 
					["GMT(+1:00) - Amsterdam", "Europe/Amsterdam"], 
					["GMT(+1:00) - Berlin", "Europe/Berlin"], 
					["GMT(+1:00) - Bern", "Europe/Zurich"], 
					["GMT(+1:00) - Zurich", "Europe/Zurich"], 
					["GMT(+1:00) - Rome", "Europe/Rome"], 
					["GMT(+1:00) - Stockholm", "Europe/Stockholm"], 
					["GMT(+1:00) - Vienna", "Europe/Vienna"], 
					["GMT(+1:00) - West Central Africa", "Africa/Algiers"], 
					["GMT(+2:00) - Bucharest", "Europe/Bucharest"], 
					["GMT(+2:00) - Cairo", "Africa/Cairo"], 
					["GMT(+2:00) - Helsinki", "Europe/Helsinki"], 
					["GMT(+2:00) - Kyiv", "Europe/Kiev"], 
					["GMT(+2:00) - Riga", "Europe/Riga"], 
					["GMT(+2:00) - Sofia", "Europe/Sofia"], 
					["GMT(+2:00) - Tallinn", "Europe/Tallinn"], 
					["GMT(+2:00) - Vilnius", "Europe/Vilnius"], 
					["GMT(+2:00) - Athens", "Europe/Athens"], 
					["GMT(+3:00) - Istanbul", "Europe/Istanbul"], 
					["GMT(+3:00) - Minsk", "Europe/Minsk"], 
					["GMT(+2:00) - Jerusalem", "Asia/Jerusalem"], 
					["GMT(+2:00) - Harare", "Africa/Harare"], 
					["GMT(+2:00) - Pretoria", "Africa/Johannesburg"], 
					["GMT(+2:00) - Kaliningrad", "Europe/Kaliningrad"], 
					["GMT(+3:00) - Moscow", "Europe/Moscow"], 
					["GMT(+3:00) - St: Petersburg", "Europe/Moscow"], 
					["GMT(+4:00) - Volgograd", "Europe/Volgograd"], 
					["GMT(+4:00) - Samara", "Europe/Samara"], 
					["GMT(+3:00) - Kuwait", "Asia/Kuwait"], 
					["GMT(+3:00) - Riyadh", "Asia/Riyadh"], 
					["GMT(+3:00) - Nairobi", "Africa/Nairobi"], 
					["GMT(+3:00) - Baghdad", "Asia/Baghdad"], 
					["GMT(+3:30) - Tehran", "Asia/Tehran"], 
					["GMT(+4:00) - Abu Dhabi", "Asia/Muscat"], 
					["GMT(+4:00) - Muscat", "Asia/Muscat"], 
					["GMT(+4:00) - Baku", "Asia/Baku"], 
					["GMT(+4:00) - Tbilisi", "Asia/Tbilisi"], 
					["GMT(+4:00) - Yerevan", "Asia/Yerevan"], 
					["GMT(+4:30) - Kabul", "Asia/Kabul"], 
					["GMT(+5:00) - Ekaterinburg", "Asia/Yekaterinburg"], 
					["GMT(+5:00) - Islamabad", "Asia/Karachi"], 
					["GMT(+5:00) - Karachi", "Asia/Karachi"], 
					["GMT(+5:00) - Tashkent", "Asia/Tashkent"], 
					["GMT(+5:30) - Chennai", "Asia/Kolkata"], 
					["GMT(+5:30) - Kolkata", "Asia/Kolkata"], 
					["GMT(+5:30) - Mumbai", "Asia/Kolkata"], 
					["GMT(+5:30) - New Delhi", "Asia/Kolkata"], 
					["GMT(+5:45) - Kathmandu", "Asia/Kathmandu"], 
					["GMT(+6:00) - Astana", "Asia/Dhaka"], 
					["GMT(+6:00) - Dhaka", "Asia/Dhaka"], 
					["GMT(+5:30) - Sri Jayawardenepura", "Asia/Colombo"], 
					["GMT(+6:00) - Almaty", "Asia/Almaty"], 
					["GMT(+7:00) - Novosibirsk", "Asia/Novosibirsk"], 
					["GMT(+6:30) - Rangoon", "Asia/Rangoon"], 
					["GMT(+7:00) - Bangkok", "Asia/Bangkok"], 
					["GMT(+7:00) - Hanoi", "Asia/Bangkok"], 
					["GMT(+7:00) - Jakarta", "Asia/Jakarta"], 
					["GMT(+7:00) - Krasnoyarsk", "Asia/Krasnoyarsk"], 
					["GMT(+8:00) - Beijing", "Asia/Shanghai"], 
					["GMT(+8:00) - Chongqing", "Asia/Chongqing"], 
					["GMT(+8:00) - Hong Kong", "Asia/Hong_Kong"], 
					["GMT(+6:00) - Urumqi", "Asia/Urumqi"], 
					["GMT(+8:00) - Kuala Lumpur", "Asia/Kuala_Lumpur"], 
					["GMT(+8:00) - Singapore", "Asia/Singapore"], 
					["GMT(+8:00) - Taipei", "Asia/Taipei"], 
					["GMT(+8:00) - Perth", "Australia/Perth"], 
					["GMT(+8:00) - Irkutsk", "Asia/Irkutsk"], 
					["GMT(+8:00) - Ulaanbaatar", "Asia/Ulaanbaatar"], 
					["GMT(+9:00) - Seoul", "Asia/Seoul"], 
					["GMT(+9:00) - Osaka", "Asia/Tokyo"], 
					["GMT(+9:00) - Sapporo", "Asia/Tokyo"], 
					["GMT(+9:00) - Tokyo", "Asia/Tokyo"], 
					["GMT(+9:00) - Yakutsk", "Asia/Yakutsk"], 
					["GMT(+9:30) - Darwin", "Australia/Darwin"], 
					["GMT(+9:30) - Adelaide", "Australia/Adelaide"], 
					["GMT(+10:00) - Canberra", "Australia/Melbourne"], 
					["GMT(+10:00) - Melbourne", "Australia/Melbourne"], 
					["GMT(+10:00) - Sydney", "Australia/Sydney"], 
					["GMT(+10:00) - Brisbane", "Australia/Brisbane"], 
					["GMT(+10:00) - Hobart", "Australia/Hobart"], 
					["GMT(+10:00) - Vladivostok", "Asia/Vladivostok"], 
					["GMT(+10:00) - Guam", "Pacific/Guam"], 
					["GMT(+10:00) - Port Moresby", "Pacific/Port_Moresby"], 
					["GMT(+11:00) - Magadan", "Asia/Magadan"], 
					["GMT(+11:00) - Srednekolymsk", "Asia/Srednekolymsk"], 
					["GMT(+11:00) - Solomon Is:", "Pacific/Guadalcanal"], 
					["GMT(+11:00) - New Caledonia", "Pacific/Noumea"], 
					["GMT(+12:00) - Fiji", "Pacific/Fiji"], 
					["GMT(+12:00) - Kamchatka", "Asia/Kamchatka"], 
					["GMT(+12:00) - Marshall Is:", "Pacific/Majuro"], 
					["GMT(+12:00) - Auckland", "Pacific/Auckland"], 
					["GMT(+12:00) - Wellington", "Pacific/Auckland"], 
					["GMT(+13:00) - Nuku'alofa", "Pacific/Tongatapu"], 
					["GMT(+13:00) - Tokelau Is:", "Pacific/Fakaofo"], 
					["GMT(+12:45) - Chatham Is:", "Pacific/Chatham"], 
					["GMT(+13:00) - Samoa", "Pacific/Apia"]
				] 
		return arr
	end

end